services:
  mariadb:
    image: mariadb:latest
    container_name: contactmanager_mariadb_dev_prealpha
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: intranet_home
      MARIADB_USER: kenneth
      MARIADB_PASSWORD: kenneth
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contactmanager_phpmyadmin_dev_prealpha
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  blazorapp:
    image: blazorapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contactmanager_blazor_dev_prealpha
    depends_on:
      - mariadb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    tty: true
    stdin_open: true

volumes:
  db_data:
