services:
  blazorapp:
    image: blazorapp:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/src  # Mount the project directory
      - /app/bin  # Persist the compiled output
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    command: "dotnet watch run --urls=http://0.0.0.0:80"