version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superman
      MYSQL_DATABASE: intranet_home
      MYSQL_USER: chad
      MYSQL_PASSWORD: gigachad
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000" # Map host port 8080 to container port 80
    volumes:
      - ./:/app # Mount the current directory to /app in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mariadb_data:
