// <auto-generated />
using ContactManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManagement.Migrations
{
    [DbContext(typeof(IntranetHomeContext))]
    [Migration("20240929225855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContactManagement.Models.Contact", b =>
                {
                    b.Property<int>("Pkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("pkid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pkid"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("alamat");

                    b.Property<string>("AlamatLain")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("alamat_lain");

                    b.Property<string>("Autoid")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("autoid");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("Email")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("email");

                    b.Property<string>("Faxno")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("faxno")
                        .HasDefaultValueSql("''''");

                    b.Property<string>("Hpno")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("hpno");

                    b.Property<string>("Kontak")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("kontak");

                    b.Property<string>("MultiDeskripsi")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("multi_deskripsi");

                    b.Property<string>("Nama")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("Telpno")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("telpno");

                    b.HasKey("Pkid")
                        .HasName("PRIMARY");

                    b.ToTable("contact_managemen", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
